services:
  frontend:
    build: frontend
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - server
    restart: unless-stopped

  server:
    build: server
    env_file:
      - ./server/.env
    volumes:
      - /srv/theater/db:/app/db
      - /srv/theater/data:/app/data
    restart: unless-stopped
